rackerlabs/simpl

- simpl/config.py
- tests/test_config.py
meta config options allow an entire configuration to be
specified by a single source. the only existing native
capability was the use of ini files, but there was no
way to specify which ini file, much less specify it the
same way any other Option could be specified (cli, env, keyring).
this connects a metaconfig instance that can be used to provision
an entire (or part of) a Config. the first meta option to be
implemented was `--ini` since Config natively supports parsing ini
files.
See the MetaConfig docstring for more details.
> feat(metaconfig): for new config sources, add groupable options and refactor mutual exclusion

- README.md
- simpl/config.py
- simpl/log.py
- tests/test_log.py
The simpl.logging module encapsulates some common
logging boilerplate. It also integrates with the
config module to support configuring logging using
command-line arguments, environment variables,
config files, and such.
> feat(logging): add logging module

- setup.py
- simpl/__about__.py
- simpl/__init__.py
Puts all package information into `simpl/__about__.py` for an improved layout and cleaner  `simpl/__init__.py` and `setup.py` 
This PR bumps the version to `0.2.2` and I'll cut a release after.
> Package info simplification and reorganization

- README.md
- all-requirements.txt
- simpl/rest.py
- tests/test_rest.py
This adds the first of the `rest.py` helpers that handle common bottle needs when implementing our APIs. Needs such as parsing the body and query params.
> feat(rest): add REST API Helpers v1

- simpl/__about__.py
- simpl/__init__.py
Remove `from simpl import git.py` from `simpl/__init__.py` so the git
module warnings don't occur even when it is not being used.
> fix(git import)

- simpl/config.py
- simpl/exceptions.py
- simpl/git.py
- tests/test_config.py
- tests/test_git.py
This change raises exceptions on these conditions:
- an explicitly defined ini file does not exist
- a config option found in a loaded ini file
does not correspond to a `config.Option`
Add `SimplConfigException` and `SimplConfigUnknownOption`
`SimplConfigUnknownOption` will be thrown if an ini file is
explicitly specified, but there are options in it that have
no match, i.e. no corresponding `config.Option`
Previously, if these conditions occurred, nothing would happen. @Gifflen spent quite a long time trying to figure out why the options defined in his ini file were not getting picked up by simpl.
> --ini error conditions

- simpl/config.py
- tests/test_config.py
Defaults were being always overwritten by suppress
which prevented them from being returned. Fixing
that exposed an issue were the metaconfig was
always returning a “Default: None” in its help
string, so that had to be suppressed.
A test was added to check this.
Fixes #26
> fix(config): formatter_class not working

- .travis.yml
- README.md
Since we are already outputting coverage data in tox I've added support for historically tracking coverage with coveralls.io. There are also badges for travis and coveralls on the README.md
> Add coveralls support

- simpl/incubator/dicts.py
The old code would build a range (a list) and iterate over it, binding
an unused name in the process.
The new code multiplies a singleton list, which is handled internally
as a simple for-loop that copies the single element into all entries
in the new list.
> chore(dicts): simplify list generation code

- pylintrc
- simpl/git.py
- test-requirements.txt
- tox.ini
We use pylint in most of our codebases, many devs
add it to their dev cycle, and we commonly include pylint comments in our code which can help declare
intent when we have code that could be flagged by
pylint.
Notes: this does not block builds or tests
> chore(style): add pylint checks

- simpl/rest.py
- test-requirements.txt
- tests/test_rest.py
Bottle returns error information by default as an
HTML page. But for writing APIs (which is what
simpl is used for mostly) we need to return
API-parseable code. This formatter ensures errors
are returned in the format requested by the client
and using a known format (dict with predictable
keys and schema).
Note: this is ported from internal projects with minor tweaks to make it generic and test to increase coverage.
> feat(rest): add error formatter

- all-requirements.txt
- simpl/incubator/rest.py
- tests/incubator/test_rest.py
It's a work-in-progress.
How to use:
```python
import bottle
from simpl import rest
import voluptuous as volup
FOO_QUERY_SCHEMA = volup.Schema({
'a': rest.coerce_many(int),
'b': rest.coerce_one(str),
})
@bottle.route('/foo')
@rest.schema(query_schema=FOO_QUERY_SCHEMA)
def foo(body=None, query=None):
return dict(body=body, query=query)
def start():
"""Start a Juno Server."""
app = bottle.default_app()
bottle.run(app=app, host='0.0.0.0', port=8080)
if __name__ == '__main__':
start()
```
Since some endpoints might want to accept multiple values for a given query parameter, the `One` and `Many` functions allow that to be specified and handled nicely.
This is somewhat opinionated for `bottle`, since query params from bottle requests are group into dicts of lists, keyed by the parameter name.
> [incubator.rest] Request schema validation deco 

- CONTRIBUTING.md
A master list of external (third-party) packages consistently used
across our projects. The first pass at this list is not considered
comprehensive and this list is expected to change frequently as we
discover better tools than the ones we currently use.
> chore(Add Library Standards)

- simpl/rest.py
- tests/test_rest.py
The decorator was not tested with a callable that
has kwargs in it’s signature. It failed if a kwarg
is passed. This adds a test for that and fixes the
bug.
> fix(rest): `rest.body` decorator missing kwargs

- README.md
- simpl/chronos.py
- tests/test_chronos.py
This ports existing code and tests (and adds new
tests to achieve 100% coverage) from existing
projects.
> feat(chronos): add date/time handling module

- README.md
- simpl/db/mongodb.py
- simpl/rest.py
- test-requirements.txt
- tests/test_db_mongodb.py
- tests/test_rest.py
When a text index exists on a collection and we want to search it using a `q=` query param, these patches can do that.
> Add Text Search Parsing

- simpl/middleware/context.py
- tests/test_middleware_context.py
Some threads can be reused by a bottle server and
old call data can persist in the thread-local
storage. This ensures the data is cleared after
each request.
> fix(context): clear call context when done

- simpl/db/mongodb.py
- tests/test_db_mongodb.py
Since we’re coding this specifically to work with
bottle and mongodb, multiple filters should be
formatted as a mongodb $in filter condition.
> fix(rest): filters must come back in mongo format

- simpl/README.md
- simpl/config.py
- tests/test_config.py
This refactor/enhancement to `simpl.config` should help address recurring issues and increasing complexity in that module caused, IMO, but trying to overload parsing and validation in `parse_cli`. It's been problematic - see #89, #79 among other bugs.
> Config: Refactor of CLI Parsing, Validation, and Precedence Handling

- README.md
- simpl/exceptions.py
- simpl/middleware/errors.py
- simpl/rest.py
- tests/test_middleware_errors.py
- tests/test_rest.py
Includes an updated error formatting function and custom httperror class.
We need to deprecate/remove and maybe add backwards compatibility for the following:
- https://github.com/checkmate/simpl/blob/v0.7.1/simpl/rest.py#L306-L368
- https://github.com/checkmate/simpl/blob/v0.7.1/simpl/rest.py#L33-L41
The current pull request is an update/upgrade/refactor of these.
The suggested use of bottle for consistent error handling and formatting becomes:
```python
app = bottle.default_app()
app.catchall = False
app.default_error_handler = rest.format_error_response
app = FormatExceptionMiddleware(app)
bottle.run(app=app)
```
This allows your app to handle unexpected exceptions in your routehandler logic OR in other middleware. Turning catchall off is beneficial in case any error handling logic …
> FormatExceptionMiddleware

- simpl/rest.py
- simpl/secrets.py
As noted by @mgeisler, KeyboardInterrupt and
SystemExit do not inherit from Exception (they
inherit from BaseException). So they will not be
caught by `except Exception`. Therefore they don’t
need to be caught explicitly and reraised.
> fix(exceptions): drop unnecessary except/raises

- .travis.yml
- README.md
- pylintrc
- setup.py
- simpl/cli.py
- simpl/config.py
- simpl/git.py
- simpl/incubator/rest.py
- simpl/log.py
- simpl/rest.py
- simpl/server.py
- simpl/utils/cli.py
- tests/incubator/test_rest.py
- tests/test_cli.py
- tests/test_server.py
- tests/test_simpl_server.py
- tox.ini
This change installs a `simpl` command into your environment during package installation using the `console_scripts` entry point. The first available subcommand is `server`. You can now use `simpl server` to quickly run your app.
The interface is similar to that of [bottle's "command line interface"](http://bottlepy.org/docs/dev/tutorial.html#command-line-interface).
Example:
```python
import bottle
@bottle.get('/')
def hello():
return 'Hello World!'
```
Run the command
```
simpl server -a test_app -p 8888
Bottle v0.12.8 server starting up (using XTornadoServer())...
Listening on http://127.0.0.1:8888/
Hit Ctrl-C to quit.
```
test it...
```
you@localhost $ http get localhost:8888
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.2
Hello …
```
> simpl server

- .gitignore
- README.md
- docs/requirements.txt
- simpl/config.py
- simpl/incubator/rest.py
- simpl/rest.py
- simpl/server.py
- test-requirements.txt
- tests/test_rest.py
Without using `functools.wraps`, the decorator will mask the underlying stack of functions.
> fix(rest): Properly wrap rest.body decorator
